name: CICD

on:
  workflow_dispatch: 

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        run: echo "cloning the code"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build the code
        run: echo "build the code using docker"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test the code
        run: echo "test the code"

  deploy:
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: deploying the code
        run: echo "deploying the code"
